export const CART_PRODUCT_SUCCESS = "CART_PRODUCT_SUCCESS";
export const CART_PRODUCT_REQUEST = "CART_PRODUCT_REQUEST";
export const CART_PRODUCT_FAILURE = "CART_PRODUCT_FAILURE";
export const CART_QUANTITY="CART_QUANTITY"
export const CART_ADD_PRODUCT_SUCCESS="CART_ADD_PRODUCT_SUCCESS"